if (NOT PYTHON_BASENAME)
    message(STATUS "Using default python: -python2.7")
    SET(PYTHON_BASENAME -python2.7)
endif()
include(/usr/local/Cellar/pyside/1.2.2/lib/cmake/PySide-1.2.2/PySideConfig${PYTHON_BASENAME}.cmake)
